
FPS = 60

# game screen
WIDTH = 480
HEIGHT = 360

STEP_X = 60
STEP_Y = 20

N_X = WIDTH // STEP_X
N_Y = HEIGHT // STEP_Y

PADDLE_COLORS = {
    1: '#686969',  # '#89CFEF'
    2: '#959696',
    3: '#D0D0C5',
    4: 'white'
}

# 'black', '#131E3A', '#022D36', 
SCREEN_COLOR = 'black'
GAME_SCREEN_COLOR = 'black'



SPEED = 300

BORDERS = {
    'BORDER_FRAME_BARELL': 10,
    'BORDER_FRAME_BOTTOM': 10,
    'BORDER_FRAME_TOP': 50
}

MAIN_HEIGHT = HEIGHT + BORDERS['BORDER_FRAME_BOTTOM'] + BORDERS['BORDER_FRAME_TOP']
MAIN_WIDTH = WIDTH + 2 * BORDERS['BORDER_FRAME_BARELL']


